# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0008_auto_20171009_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runner_profile',
                                      to='core.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField(default=-1)),
                ('description', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(-1, 'Pending'), (0, 'Sent')], default=-1)),
                ('command', models.CharField(max_length=1000)),
                ('data', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
