# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 13:00
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=500)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('assigned_to', models.CharField(blank=True, max_length=50)),
                ('created_on', models.DateTimeField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_synced', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(default='latest', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(blank=True, max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('keyword', models.CharField(max_length=100)),
                ('priority',
                 models.IntegerField(choices=[(0, 'Urgent'), (1, 'High'), (2, 'Medium'), (3, 'Low')], default=2)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=50)),
                ('created_by', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=50)),
                ('status', models.CharField(default='Ready', max_length=50)),
                ('detail', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.IntegerField(
                    choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Aborted'), (3, 'Skipped'), (4, 'manual passed')])),
                ('output', models.TextField(default='...')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('assigned_to', models.CharField(max_length=50)),
                ('is_rerun', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               to='core.ResultAnalysis')),
                ('test_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.TestClient')),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('start_by', models.CharField(max_length=50)),
                ('state',
                 models.IntegerField(choices=[(0, 'Starting'), (1, 'Running'), (2, 'Aborted'), (3, 'Completed')])),
                ('status', models.IntegerField(
                    choices=[(0, 'Passed'), (1, 'Analysis Required'), (2, 'Analyzed'), (3, 'Abandoned')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TestRun'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.TestCase'),
        ),
    ]
