# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='state',
            field=models.IntegerField(
                choices=[(-1, 'Not Ready'), (0, 'Starting'), (1, 'Running'), (2, 'Aborted'), (3, 'Completed')],
                default=-1),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.IntegerField(
                choices=[(-1, 'Pending'), (0, 'Passed'), (1, 'Analysis Required'), (2, 'Analyzed'), (3, 'Abandoned')],
                default=-1),
        ),
    ]
