# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:31
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20170622_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultanalysis',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='analysis', to='core.Issue'),
        ),
    ]
