# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 09:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20170609_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
            preserve_default=False,
        ),
    ]
