# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 01:48
from __future__ import unicode_literals

from django.db import migrations, models

import testcube.core.models.result_file


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20170902_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultfile',
            name='path',
        ),
        migrations.AddField(
            model_name='resultfile',
            name='file',
            field=models.FileField(default='', upload_to=testcube.core.models.result_file.run_file_dir),
            preserve_default=False,
        ),
    ]
