# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20170626_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
