# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 05:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20170609_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFailure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('stacktrace', models.TextField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='output',
        ),
        migrations.AddField(
            model_name='testresult',
            name='error',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='core.TestFailure'),
        ),
    ]
