# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 02:25
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20170905_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultfile',
            name='file_byte_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultfile',
            name='file_created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
