# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 03:49
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20170905_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultfile',
            name='file_created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
