# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20170610_0506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestFailure',
            new_name='ResultError',
        ),
    ]
