# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 01:39
from __future__ import unicode_literals

from django.db import migrations, models

import testcube.core.models.result_file


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_auto_20170905_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultfile',
            name='file',
            field=models.FileField(max_length=255, upload_to=testcube.core.models.result_file.run_file_dir),
        ),
    ]
