# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 09:34
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_auto_20170610_0541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='start_time',
        ),
        migrations.AddField(
            model_name='testresult',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
