# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 02:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_auto_20170911_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.IntegerField(
                    choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Skipped'), (3, 'Error'), (4, 'Manual Passed')])),
                ('stdout', models.TextField(blank=True, default=None, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('reset_on', models.DateTimeField(blank=True, null=True)),
                ('reset_by', models.CharField(blank=True, max_length=50)),
                ('reset_status',
                 models.IntegerField(choices=[(0, 'None'), (1, 'In Progress'), (2, 'Done'), (3, 'Failed')], default=0)),
                ('error', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='reset_result', to='core.ResultError')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='is_rerun',
        ),
        migrations.AddField(
            model_name='resetresult',
            name='origin_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_results',
                                    to='core.TestResult'),
        ),
        migrations.AddField(
            model_name='resetresult',
            name='test_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reset_results',
                                    to='core.TestClient'),
        ),
    ]
