# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_auto_20170610_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='full_name',
            field=models.CharField(default=models.CharField(max_length=200), max_length=400),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
