# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_auto_20171009_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resetresult',
            options={'ordering': ['-reset_on']},
        ),
        migrations.RemoveField(
            model_name='resetresult',
            name='created_on',
        ),
        migrations.AddField(
            model_name='resetresult',
            name='reset_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resetresult',
            name='run_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resetresult',
            name='outcome',
            field=models.IntegerField(
                choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Skipped'), (3, 'Error'), (4, 'Manual Passed'),
                         (5, 'Pending')], default=5),
        ),
        migrations.AlterField(
            model_name='resetresult',
            name='reset_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='outcome',
            field=models.IntegerField(
                choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Skipped'), (3, 'Error'), (4, 'Manual Passed'),
                         (5, 'Pending')]),
        ),
    ]
