# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_auto_20171009_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetresult',
            name='test_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='reset_results', to='core.TestClient'),
        ),
    ]
