# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_auto_20170610_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='full_name',
            field=models.CharField(default='', max_length=400),
        ),
    ]
