# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_auto_20170610_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
